### ISSUE TITLE
Exception on dragging the child widget for version 3.1.6

### ISSUE THREAD

**Issue by Farley-Chen** [alnitak/flutter_star_menu#18]
Run on windows.

Version 3.1.4 do not have this exception.

But version 3.1.6 have this exception.

Dragging the child widget when menu is open can encounter this exception.

Here is the example

```dart
import 'package:flutter/material.dart';
import 'package:star_menu/star_menu.dart';

main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Container(
        width: 100,
        height: 100,
        color: Colors.blue,
      ).addStarMenu(
          params: const StarMenuParameters(
              backgroundParams:
                  BackgroundParams(backgroundColor: Colors.black12)),
          items: [
            Container(
              width: 10,
              height: 10,
              color: Colors.black,
            )
          ]),
    );
  }
}
```

When drag the container some error happened like this

```log
Performing hot restart...
Syncing files to device Windows...
Restarted application in 406ms.
flutter: MOVE 1.885618083164125 -0.07 6.213185307179586
flutter: MOVE 3.887301263230196 -0.14 6.143185307179586

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
The third row and third column of a transform matrix for pointer events must be Vector4(0, 0, 1, 0) to ensure that a transformed point is directly under the pointing device. Did you forget to run the paint matrix through PointerEvent.removePerspectiveTransform? The provided matrix is:
[0] NaN,NaN,NaN,NaN
[1] NaN,NaN,NaN,NaN
[2] NaN,NaN,NaN,NaN
[3] NaN,NaN,NaN,NaN
'package:flutter/src/gestures/hit_test.dart':
Failed assertion: line 212 pos 7: '_debugVectorMoreOrLessEquals(transform.getRow(2), Vector4(0, 0, 1, 0)) &&
      _debugVectorMoreOrLessEquals(transform.getColumn(2), Vector4(0, 0, 1, 0))'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      HitTestResult.pushTransform (package:flutter/src/gestures/hit_test.dart:212:7)
#3      BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:834:7)
#4      BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:766:12)
#5      RenderTransform.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2506:19)
#6      RenderTransform.hitTest (package:flutter/src/rendering/proxy_box.dart:2500:12)
#7      RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2861:25)
#8      BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:800:31)
#9      RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2856:33)
#10     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:631:12)
#11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#12     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
#13     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#14     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
#15     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#16     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1984:18)
#17     _RenderTheaterMixin.hitTestChildren.childHitTest (package:flutter/src/widgets/overlay.dart:902:81)
#18     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:800:31)
#19     _RenderTheaterMixin.hitTestChildren (package:flutter/src/widgets/overlay.dart:903:22)
#20     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#21     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
#22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#23     RenderAbsorbPointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3843:17)
#24     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
#25     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:172:19)
#26     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
#27     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#28     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
#29     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:559:18)
#30     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#31     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
#32     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#33     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
#34     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#35     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
#36     RenderTapRegionSurface.hitTest (package:flutter/src/widgets/tap_region.dart:213:28)
#37     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
#38     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#39     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
#40     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#41     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
#42     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#43     RenderView.hitTest (package:flutter/src/rendering/view.dart:211:14)
#44     RendererBinding.hitTestInView (package:flutter/src/rendering/binding.dart:624:34)
#45     RendererBinding.initMouseTracker.<anonymous closure> (package:flutter/src/rendering/binding.dart:425:7)
#46     MouseTracker._findAnnotations (package:flutter/src/rendering/mouse_tracker.dart:261:60)
#47     MouseTracker.updateAllDevices.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:375:80)
#48     MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:210:9)
#49     MouseTracker.updateAllDevices (package:flutter/src/rendering/mouse_tracker.dart:372:5)
#50     RendererBinding._scheduleMouseTrackerUpdate.<anonymous closure> (package:flutter/src/rendering/binding.dart:474:22)
#51     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#52     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1264:9)
#53     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#54     _invoke (dart:ui/hooks.dart:312:13)
#55     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#56     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

**Comment by alnitak** [comment]
Hi @Farley-Chen,

thank you for finding this issue! I left a bunch of unused code when trying to make circle menu items to spin!!
I have updated this to v3.1.7 also on pub.dev

Let me know if all is ok now, feel free to reopen this issue.
